dist:
  - bionic
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
  - pip install -r doc/requirements.txt
  - pip install .
script:
  - python -c "import keras_gym"  # patches tensorflow
  - flake8 keras_gym
  - pytest keras_gym
